[global]
ignore_file = " Makefile.ini, Makefile";
ignore_dir = "";

[target#0]
target = "etc/";
target_param = "644"
target_user = "swan";
target_group = "swan";
target_dir_param = "755"
target_dir_user = "swan";
target_dir_group = "swan";
