language: php
php:
    - 5.3
    - 5.4
    - 5.5
before_script:
    - cd tests
    - mysql -e 'create database swan_soft;'
    - mysql -e 'CREATE DATABASE guestbook;'
    - pear config-set auto_discover 1
    - pear install pear.phpunit.de/PHPUnit
    - pear install phpunit/DbUnit

script: phpunit -v
notifications:
    email:
        - nmred_2008@126.com
