language: php
php:
    - 5.3
    - 5.4
    - 5.5
before_script:
    - mysql -e 'create database swan_soft;'
    - mysql -u root swan_soft tests/db_desc_swan_soft.sql
    - pear config-set auto_discover 1
    - pear install pear.phpunit.de/PHPUnit
    - pear install phpunit/DbUnit
    - cd tests

script: phpunit -v
notifications:
    email:
        - nmred_2008@126.com
