language: php
php:
    - 5.3
    - 5.4
    - 5.5
before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --no-interaction
    - mysql -e 'create database swan_soft;'
    - mysql -e 'use swan_soft;'
    - mysql -e 'source src/tmp_install/sql/db_desc_swan_soft.sql;'
    - echo "<?php return array('db' => array('type' => 'mysql', 'dbname' => 'swan_soft', 'username' => 'root', 'password' => '', 'host' => '127.0.0.1', 'port' => '3306', 'driver_options' => array()));" > src/inc/conf/config.php

script:
  - mkdir -p build/logs
  - mkdir -p build/coverage
  - php vendor/bin/phpunit -v --coverage-clover build/logs/clover.xml 

after_script:
  - php vendor/bin/phpcov.php --merge --clover build/logs/clover.xml --whitelist library build/coverage
  - cat build/logs/clover.xml
  - php vendor/bin/coveralls  -v

notifications:
    email:
        - swansoft_team@groups.163.com
