#!/bin/bash

/usr/local/swan/smeta/opt/mysql/bin/mysql -uroot -S /usr/local/swan/smeta/run/sw_mysql.sock </usr/local/swan/smeta/tmp_install/sql/db_clear.sql
/usr/local/swan/smeta/opt/mysql/bin/mysql -uroot -S /usr/local/swan/smeta/run/sw_mysql.sock </usr/local/swan/smeta/tmp_install/sql/db_desc_swan_soft.sql
